CREATE DATABASE HROADS;
GO

USE HROADS;
GO

CREATE TABLE Classe(
 idClasse TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeClasse VARCHAR(40) NOT NULL 
);

CREATE TABLE TipoUsuario(
 idTipoUsuario TINYINT PRIMARY KEY IDENTITY(1,1),
 Titulo VARCHAR(40) NOT NULL 
);

CREATE TABLE Usuario(
 idUsuario TINYINT PRIMARY KEY IDENTITY,
 idTipoUsuario TINYINT FOREIGN KEY REFERENCES TipoUsuario(idTipoUsuario),
 Email VARCHAR(100),
 Senha CHAR(10)
);

CREATE TABLE TipoHabilidade(
 idTipoHabilidade TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeTipo VARCHAR(40) NOT NULL
);

CREATE TABLE Habilidade(
 idHabilidade TINYINT PRIMARY KEY IDENTITY(1,1),
 idTipoHabilidade TINYINT FOREIGN KEY REFERENCES TipoHabilidade(idTipoHabilidade),
 nomeHabilidade VARCHAR(40) NOT NULL
);


CREATE TABLE ClassesHabilidades(
 idClassesHabilidades TINYINT PRIMARY KEY IDENTITY(1,1),
 idHabilidade TINYINT FOREIGN KEY REFERENCES Habilidade(idHabilidade),
 idClasse TINYINT FOREIGN KEY REFERENCES Classe(idClasse),
);

CREATE TABLE Personagem(
 idPersonagem TINYINT PRIMARY KEY IDENTITY(1,1),
 nomePersonagem VARCHAR(40) NOT NULL,
 idClasse TINYINT FOREIGN KEY REFERENCES Classe(idClasse),
 Vida TINYINT NOT NULL,
 Mana TINYINT NOT NULL,
 dataCriacao DATETIME,
 dataAtualizacao DATETIME
);


DROP DATABASE HROADS
